- name: Create directories for 3x-ui
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/3xui/db
    - /opt/3xui/cert

- name: Render 3xui docker compose file
  ansible.builtin.template:
    src: docker-compose.3xui.yml.j2
    dest: /opt/3xui/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Start 3xui with docker compose
  community.docker.docker_compose_v2:
    project_src: /opt/3xui
    state: present