- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow required ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"
    - "80"
    - "443"
    - "8443"
    - "30000:40000"

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny