- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow required ports (TCP + UDP)
  community.general.ufw:
    rule: allow
    port: "{{ item.0 }}"
    proto: "{{ item.1 }}"
  loop: "{{ ports | product(['tcp', 'udp']) | list }}"
  vars:
    ports:
      - "22"
      - "80"
      - "443"
      - "8443"
      - "10000:65535"

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny